version: "2"
services:
    main:
        hostname: jenkins-main01
        build:
            context: .
            dockerfile: Dockerfile.main
        ports:
            - "80:8080"
        networks:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock    
    
    worker01:
        hostname: jenkins-worker01
        build:
            context: .
            dockerfile: Dockerfile.deb.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock    
    worker02:
        hostname: jenkins-worker02
        build:
            context: .
            dockerfile: Dockerfile.rpm.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock   
networks:
    jenkins:
